version: '3'

services:
  db:
    image: sqlite:latest
    volumes:
      - sql_data:/data
    environment:
      - SQLITE_DATABASE=/app.db
   
  myapp:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=sqlite:///app.db
volumes:
  sql_data: